version: '3.8'

services:
  stealerlogs-opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: stealerlogs-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.restapi.roles_enabled=["all_access"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - stealerlogs-opensearch-net

  stealerlogs-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: stealerlogs-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://stealerlogs-opensearch:9200
      - OPENSEARCH_SSL_VERIFICATION_MODE=none
      - OPENSEARCH_SECURITY_MULTITENANCY_ENABLED=false
      - OPENSEARCH_SECURITY_AUTH_DISABLE_LOGIN_FORM=true
      - OPENSEARCH_SECURITY_AUTH_ANONYMOUS_ENABLE=true
      - OPENSEARCH_DASHBOARDS_ALLOW_ROLES=*
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ports:
      - "5601:5601"
    networks:
      - stealerlogs-opensearch-net
    depends_on:
      - stealerlogs-opensearch

networks:
  stealerlogs-opensearch-net:
    driver: bridge
