services:
  stealerlogs-opensearch:
    image: opensearchproject/opensearch:latest
    container_name: stealerlogs-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - opensearch-logs:/usr/share/opensearch/logs
      - opensearch-config:/usr/share/opensearch/config
    networks:
      - stealerlogs-opensearch-net

  stealerlogs-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: stealerlogs-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://stealerlogs-opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    volumes:
      - opensearch-dashboard-config:/usr/share/opensearch-dashboards/config
      - opensearch-dashboard-logs:/usr/share/opensearch-dashboards/logs
    networks:
      - stealerlogs-opensearch-net
    depends_on:
      - stealerlogs-opensearch

networks:
  stealerlogs-opensearch-net:
    driver: bridge

volumes:
  opensearch-data:
  opensearch-logs:
  opensearch-config:
  opensearch-dashboard-config:
  opensearch-dashboard-logs: