version: '3.8'

services:
  stealerlogs-opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: stealerlogs-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  stealerlogs-opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: stealerlogs-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://stealerlogs-opensearch:9200
      - OPENSEARCH_SSL_VERIFICATION_MODE=none
    ports:
      - "5601:5601"
    networks:
      - opensearch-net
    depends_on:
      - stealerlogs-opensearch

networks:
  opensearch-net:
    driver: bridge
